# Generated by Django 5.0.13 on 2025-04-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseData', '0001_initial'),
        ('studentsData', '0003_course_date_added'),
        ('teachersData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='courseData.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='courseData.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(to='teachersData.teacher'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
