# Generated by Django 5.0.14 on 2025-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsData', '0007_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
