# Generated by Django 5.0.13 on 2025-04-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(auto_created=True, default='rfaefc56', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
