# Generated by Django 5.0.13 on 2025-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersData', '0003_teacher_city_teacher_state_alter_teacher_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(auto_created=True, editable=False, max_length=50, unique=True),
        ),
    ]
