# Generated by Django 5.0.13 on 2025-04-20 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersData', '0006_alter_teacher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='years_of_experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
