# Generated by Django 5.0.14 on 2025-09-02 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersData', '0007_alter_teacher_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='years_of_experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
