# Generated by Django 5.0.14 on 2025-09-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersData', '0008_alter_teacher_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/'),
        ),
    ]
