# Generated by Django 5.0.13 on 2025-04-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='code',
            new_name='course_code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
