# Generated by Django 5.0.14 on 2025-09-03 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managersData', '0002_remove_managers_id_managers_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='username',
            field=models.CharField(default='TESTCASE', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
