# Generated by Django 5.0.14 on 2025-09-03 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managersData', '0003_managers_username_alter_managers_date_of_joining_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managers',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
